import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/main/Navbar";
import StarCanvas from "@/components/main/StarBackground";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/main/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meet Limbani | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={` ${inter.className} bg-[#030014] overflow-x-hidden ` }>
        <Navbar />
        {children}
        <Toaster position="top-right" />
        <StarCanvas />
        <Footer />
        </body>
    </html>
  );
}
